### ISSUE TITLE
API Routes

### ISSUE THREAD

**Issue by skydiver** [HaNdTriX/next-electron-server#4]
Hey @HaNdTriX 

It's possible to use api routes with this package? Have you tried?

Thanks

**Comment by HaNdTriX** [comment]
This package was build with `next export` ([Docs](https://nextjs.org/docs/advanced-features/static-html-export)) in mind.

So all features regarding runtime specific node requirements will be disabled in production. 

- https://nextjs.org/docs/advanced-features/static-html-export#caveats

I chose this approach because I don't see much benefit in using API Routes over Electrons [IPC Messaging](https://www.electronjs.org/docs/api/ipc-main#ipcmainhandlechannel-listener). 

**Off-Topic:** I might be possible to implement dynamic API Routes using [Electon Protocol handlers](https://www.electronjs.org/docs/api/protocol) and the exported handlers from `.next/server/pages/api/...`.  This will come with some runtime cost.
